### ISSUE TITLE
UnicodeEncodeError in xbmc.log

### ISSUE THREAD

**Issue by wolfgame** [kuruoujou/XBMal#15]
Figured I'd check out the current version to see if the issues had been worked out and am receiving the following error.  Is this project still active?
````
05:44:18 T:10588   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xa0' in position 29: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Bill\AppData\Roaming\XBMC\addons\script.service.xbmal\default.py", line 215, in <module>
                                                w = MainDiag()
                                              File "C:\Users\Bill\AppData\Roaming\XBMC\addons\script.service.xbmal\default.py", line 163, in __init__
                                                mappings = lg.generateList(pDialog)
                                              File "C:\Users\Bill\AppData\Roaming\XBMC\addons\script.service.xbmal\default.py", line 49, in generateList
                                                self.output.log("Checking " + season[0]['showtitle'] + " Season " + str(season[0]['season']), xbmc.LOGNOTICE)
                                              File "C:\Users\Bill\AppData\Roaming\XBMC\addons\script.service.xbmal\resources\lib\xbmal.py", line 133, in log
                                                xbmc.log("### [%s] - %s" %(__scriptname__,msg), level=loglevel)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 29: ordinal not in range(128)
                                            -->End of Python script error report<--
05:44:18 T:11528   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
05:44:18 T:10588    INFO: Python script stopped
````

**Comment by kuruoujou** [comment]
Huh. Didn't quite mean to close this from the commit, but whatever. Could you test 0.4.10 and see if you're still having that issue?

**Comment by wolfgame** [comment]
It's looking good.  Got the whole list and guessing is working for most titles.
